# Generated by Django 4.2.7 on 2025-08-31 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('test_attempted', models.IntegerField(default=0)),
                ('points', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('que', models.TextField()),
                ('a', models.CharField(max_length=255)),
                ('b', models.CharField(max_length=255)),
                ('c', models.CharField(max_length=255)),
                ('d', models.CharField(max_length=255)),
                ('ans', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_short', models.PositiveIntegerField(default=3, help_text='Time limit (minutes) when number of questions <= 5')),
                ('minutes_medium', models.PositiveIntegerField(default=10, help_text='Time limit (minutes) when 6-10 questions')),
                ('minutes_long', models.PositiveIntegerField(default=20, help_text='Time limit (minutes) when > 10 questions')),
                ('fallback_minutes_per_question', models.PositiveIntegerField(default=1, help_text='Fallback minutes per question if rules are not desired')),
                ('show_leave_warning', models.BooleanField(default=True, help_text='Warn users when leaving the page during a test')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('resultid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('attempt', models.IntegerField()),
                ('right', models.IntegerField()),
                ('wrong', models.IntegerField()),
                ('points', models.FloatField()),
                ('details', models.JSONField(blank=True, default=list)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OTS.candidate')),
            ],
            options={
                'ordering': ['-resultid'],
            },
        ),
    ]
